FROM alpine:3.11

# Defaults
ENV BROKER_HOST=broker \
    BROKER_PORT=6379 \
    DB_HOST=database \
    DB_PORT=3306 \
    DB_USER=honeysens \
    DB_NAME=honeysens \
    DB_PASSWORD=secret \
    REGISTRY_HOST=registry \
    REGISTRY_PORT=5000

RUN set -ex; \
        mkdir -p /srv/tls; \
        ln -s /srv/data/https.chain.crt /srv/tls/https.crt; \
        ln -s /srv/data/https.key /srv/tls/https.key; \
        apk --no-cache add py3-cryptography py3-watchdog py3-pip skopeo

COPY run-dev.sh /opt/run.sh

WORKDIR /mnt
CMD ["/opt/run.sh"]