FROM alpine:3.11

# Defaults
ENV HS_BROKER_HOST=broker \
    HS_BROKER_PORT=6379 \
    HS_DB_HOST=database \
    HS_DB_PORT=3306 \
    HS_DB_USER=honeysens \
    HS_DB_NAME=honeysens \
    HS_DB_PASSWORD=secret \
    HS_REGISTRY_HOST=registry \
    HS_REGISTRY_PORT=5000

RUN set -ex; \
        apk --no-cache add py3-cryptography py3-watchdog py3-pip skopeo; \
        addgroup -g 1000 hs; \
        adduser -D -u 1000 -G hs hs; \
        mkdir -p /srv/tls; \
        chown hs:hs /srv/tls

COPY run-dev.sh /opt/run.sh

WORKDIR /mnt
USER 1000:1000
CMD ["/opt/run.sh"]