FROM ubuntu:24.04
MAINTAINER Pascal Brueckner <pascal.brueckner@sylence.cc>

ARG BID
# Defaults
ENV ACCESS_LOG=false \
    BUILD_ID=$BID \
    DOMAIN=server \
    HS_APP_PATH=/mnt \
    HS_BROKER_HOST=broker \
    HS_BROKER_PORT=6379 \
    HS_DATA_PATH=/srv/data \
    HS_DB_HOST=database \
    HS_DB_PORT=3306 \
    HS_DB_USER=honeysens \
    HS_DB_NAME=honeysens \
    HS_DB_PASSWORD=secret \
    HS_DB_ROOT_PASSWORD=secret \
    HS_REGISTRY_HOST=registry \
    HS_REGISTRY_PORT=5000 \
    PLAIN_HTTP_API=false \
    TLS_FORCE_12=false

COPY env/run.sh env/setup_prepare.sh env/setup_dev.sh /opt/
RUN /bin/bash /opt/setup_prepare.sh
RUN /bin/bash /opt/setup_dev.sh

COPY env/startup.d/00_init_dev_env.sh /etc/startup.d/

USER 1000:1000
EXPOSE 8080 8443
CMD ["/opt/run.sh"]
