FROM phusion/baseimage:0.11
MAINTAINER Pascal Brueckner <pascal.brueckner@sylence.cc>

# Defaults
ENV ACCESS_LOG=false \
    BRANDING_ENABLED=no \
    BROKER_HOST=broker \
    BROKER_PORT=6379 \
    DEV_WATCH_TASK=chokidar \
    DB_HOST=database \
    DB_PORT=3306 \
    DB_USER=honeysens \
    DB_NAME=honeysens \
    DB_PASSWORD=secret \
    DOMAIN=server

COPY utils/docker/setup_prepare.sh utils/docker/setup_dev.sh /opt/
RUN /bin/bash /opt/setup_prepare.sh
RUN /bin/bash /opt/setup_dev.sh

COPY utils/docker/my_init.d/00_init_dev_env.sh /etc/my_init.d/

EXPOSE 80 443

CMD ["/sbin/my_init"]