FROM ubuntu:20.04
MAINTAINER Pascal Brueckner <pascal.brueckner@sylence.cc>

# Defaults
ENV ACCESS_LOG=false \
    BRANDING_ENABLED=no \
    HS_BROKER_HOST=broker \
    HS_BROKER_PORT=6379 \
    DEV_WATCH_TASK=chokidar \
    HS_DB_HOST=database \
    HS_DB_PORT=3306 \
    HS_DB_USER=honeysens \
    HS_DB_NAME=honeysens \
    HS_DB_PASSWORD=secret \
    DOMAIN=server \
    HS_REGISTRY_HOST=registry \
    HS_REGISTRY_PORT=5000

COPY utils/docker/run.sh utils/docker/setup_prepare.sh utils/docker/setup_dev.sh /opt/
RUN /bin/bash /opt/setup_prepare.sh
RUN /bin/bash /opt/setup_dev.sh

COPY utils/docker/startup.d/00_init_dev_env.sh /etc/startup.d/

USER 1000:1000
EXPOSE 80 443
CMD ["/opt/run.sh"]
