version: "3"
services:

  server:
    image: honeysens/server:2.4.0
    restart: always
    ports:
      # For security reasons, bind these ports to a specific IP (such as "- 192.168.1.1:443:443")
      - 80:80
      - 443:443
    networks:
      - honeysens
    environment:
      - ACCESS_LOG=false
      - API_LOG=false
      - HS_DB_PASSWORD=honeysens
      - DOMAIN=server
      - TLS_FORCE_12=false
      #- TLS_AUTH_PROXY=172.0.0.1
    volumes:
      - honeysens_data:/opt/HoneySens/data
      #- <path to https.chain.crt>:/srv/tls/https.crt
      #- <path to https.key>:/srv/tls/https.key

  database:
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default_authentication_plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=honeysens
      - MYSQL_USER=honeysens
      - MYSQL_PASSWORD=honeysens
    image: mysql:8.0
    networks:
      - honeysens
    volumes:
      - honeysens_db:/var/lib/mysql

  broker:
    image: redis:5
    restart: always
    networks:
      - honeysens

  tasks:
    image: honeysens/tasks:2.4.0
    restart: always
    environment:
      - HS_DB_PASSWORD=honeysens
    networks:
      - honeysens
    volumes:
      - honeysens_data:/srv/data
      #- <path to https.chain.crt>:/srv/tls/https.crt
      #- <path to https.key>:/srv/tls/https.key

  registry:
    image: registry:2
    restart: always
    networks:
      - honeysens
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    user: "1000:1000"
    volumes:
      - honeysens_registry:/var/lib/registry

  backup:
    image: honeysens/backup:2.4.0
    restart: always
    environment:
      - CRON_ENABLED=false
      - CRON_CONDITION=0 3 * * *
      - CRON_DBONLY=false
      - CRON_KEEP=0
      - CRON_TEMPLATE=backup-%s
      - HS_DB_PASSWORD=honeysens
    networks:
      - honeysens
    volumes:
      - honeysens_backup:/srv/backup
      - honeysens_data:/srv/data
      - honeysens_registry:/srv/registry

volumes:
  honeysens_backup:
  honeysens_data:
  honeysens_db:
  honeysens_registry:

networks:
  honeysens:
