version: "3"
services:

  server:
    image: honeysens/server:$REVISION
    restart: unless-stopped
    ports:
      # For security reasons, bind these ports to a specific IP (such as "- 192.168.1.1:443:443")
      - "80:8080"
      - "443:8443"
    networks:
      - honeysens
    environment:
      - ACCESS_LOG=false
      - API_LOG=false
      - DOMAIN=server
      - HS_DB_PASSWORD=honeysens
      - PLAIN_HTTP_API=false
      - TLS_FORCE_12=false
    volumes:
      - honeysens_data:/opt/HoneySens/data
      #- <path to server.chain.crt>:/srv/tls/server.crt
      #- <path to server.key>:/srv/tls/server.key

  database:
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default_authentication_plugin=mysql_native_password
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=honeysens
      - MYSQL_USER=honeysens
      - MYSQL_PASSWORD=honeysens
    image: mysql:8-oracle
    networks:
      - honeysens
    user: "999:999"
    volumes:
      - honeysens_db:/var/lib/mysql

  broker:
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    image: ubuntu/redis:6.0-22.04_beta
    restart: unless-stopped
    user: "101:101"
    networks:
      - honeysens

  tasks:
    image: honeysens/tasks:$REVISION
    restart: unless-stopped
    environment:
      - HS_DB_PASSWORD=honeysens
      - HS_WORKER_COUNT=auto
    networks:
      - honeysens
    volumes:
      - honeysens_data:/srv/data
      #- <path to server.chain.crt>:/srv/tls/server.crt
      #- <path to server.key>:/srv/tls/server.key

  registry:
    image: registry:2
    restart: unless-stopped
    networks:
      - honeysens
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    user: "1000:1000"
    volumes:
      - honeysens_registry:/var/lib/registry

  backup:
    image: honeysens/backup:$REVISION
    restart: unless-stopped
    environment:
      - CRON_ENABLED=false
      - CRON_CONDITION=0 3 * * *
      - CRON_DBONLY=false
      - CRON_KEEP=0
      - CRON_TEMPLATE=backup-%s
      - HS_DB_PASSWORD=honeysens
    networks:
      - honeysens
    volumes:
      - honeysens_backup:/srv/backup
      - honeysens_data:/srv/data
      - honeysens_registry:/srv/registry

volumes:
  honeysens_backup:
  honeysens_data:
  honeysens_db:
  honeysens_registry:

networks:
  honeysens:
