version: "3"
services:

  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 443:443
    networks:
      - server
    environment:
      - ACCESS_LOG=false
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=honeysens
      - DB_PASSWORD=honeysens
      - DB_NAME=honeysens
      - DOMAIN=server
      - BRANDING_ENABLED
      - DEV_WATCH_TASK
    volumes:
      - honeysens_dev_data:/srv/data
      - .:/mnt

  database:
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default_authentication_plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=honeysens
      - MYSQL_USER=honeysens
      - MYSQL_PASSWORD=honeysens
    image: mysql:8.0
    networks:
      - server
    volumes:
      - honeysens_dev_db:/var/lib/mysql

  honeysens-registry:
    image: registry:2
    networks:
      - server
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    volumes:
      - honeysens_dev_registry:/var/lib/registry

  backup:
    build: services/backup
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=honeysens
      - DB_PASSWORD=honeysens
      - DB_NAME=honeysens
    networks:
      - server
    restart: "no"
    volumes:
      - honeysens_dev_registry:/srv/registry
      - honeysens_dev_data:/srv/data

volumes:
  honeysens_dev_data:
  honeysens_dev_db:
  honeysens_dev_registry:

networks:
  server:
  proxy:
    driver: macvlan
