# -*- mode: ruby -*-
# vi: set ft=ruby :
#

Vagrant.configure("2") do |config|

  config.vm.provider "docker" do |d|
    d.build_dir = "."
    d.dockerfile = "Dockerfile.dev"
    d.build_args = ["-t", "honeysens/server-dev:1.0.4"]
    d.create_args = ["-e", "BRANDING_ENABLED=no", "-e", "DEV_WATCH_TASK=simple-watch"]
    d.ports = ["80:80", "443:443"]
    d.force_host_vm = true
    d.vagrant_vagrantfile = "Vagrantfile.boot2docker"
  end

  config.vm.synced_folder ".", "/mnt"
end
