version: "3"
services:

  sensor:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - IFACE=eth0
      #- EAPOL_IFACE=eth1
      - LOG_LVL=debug
      - DEV_WATCH_TASK
    #network_mode: host
    networks:
      - ext_sensors
      #- proxy
      - server
    privileged: true
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.host.sock
      - ../../:/mnt
      - ./conf:/etc/manager
      - docker_overlay:/var/lib/docker

volumes:
  docker_overlay: null

networks:
  ext_sensors:
  #proxy:
  server:
