services:
  web:
    build:
      args:
        BID: dev
      context: services/web
      dockerfile: Dockerfile.dev
    ports:
      - "443:8443"
    networks:
      - server
    environment:
      - ACCESS_LOG=false
      - API_LOG=true
      - DOMAIN=server
      - HS_DB_PASSWORD=honeysens
      - HS_DB_ROOT_PASSWORD=secret
      - PLAIN_HTTP_API=false
      - TLS_FORCE_12=false
    volumes:
      - vol_data:/srv/data
      - ./services/web:/mnt

  database:
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --log-error-verbosity=1 --mysql-native-password=ON
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=honeysens
      - MYSQL_USER=honeysens
      - MYSQL_PASSWORD=honeysens
    image: mysql:8-oracle
    networks:
      - server
    user: "999:999"
    volumes:
      - vol_db:/var/lib/mysql

  broker:
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    image: ubuntu/redis:6.0-22.04_beta
    user: "101:101"
    networks:
      - server

  tasks:
    build:
      args:
        BID: dev
      context: services/tasks
      dockerfile: Dockerfile.dev
    environment:
      - HS_DB_PASSWORD=honeysens
      - HS_WORKER_COUNT=auto
    networks:
      - server
    volumes:
      - vol_data:/srv/data
      - ./services/tasks:/mnt

  registry:
    image: registry:2
    networks:
      - server
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    user: "1000:1000"
    volumes:
      - vol_registry:/var/lib/registry

  backup:
    build:
      args:
        BID: dev
      context: services/backup
    environment:
      - CRON_ENABLED=false
      - CRON_CONDITION=0 3 * * *
      - CRON_DBONLY=false
      - CRON_KEEP=0
      - CRON_TEMPLATE=backup-%s
      - HS_DB_PASSWORD=honeysens
    networks:
      - server
    volumes:
      - vol_backup:/srv/backup
      - vol_data:/srv/data
      - vol_registry:/srv/registry

volumes:
  vol_backup:
  vol_data:
  vol_db:
  vol_registry:

networks:
  server:
  proxy:
    driver: macvlan
